packages:
  # Your websites/applications
  - "apps/*"
  # Shared comonents and packages
  - "packages/*"
  # exclude packages that are inside test directories
  - '!**/test/**'
  # docs
  - "docs"
  # examples
  - "examples/*"
  # examples for members
  - "examples-members/*"